// <auto-generated />
using System;
using FootballSimulator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballSimulator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FootballSimulatorDbContext))]
    [Migration("20260111080232_AddTeamStatisticAndScheduleEntities")]
    partial class AddTeamStatisticAndScheduleEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Core.Domain.EntityHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CommandTypeId")
                        .HasColumnType("int")
                        .HasColumnName("command_type_id");

                    b.Property<Guid>("EntityGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_guid");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("entity_histories");
                });

            modelBuilder.Entity("Common.Core.Domain.EntityHistoryChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityHistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_history_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityHistoryId");

                    b.ToTable("entity_history_changes");
                });

            modelBuilder.Entity("Common.Core.Domain.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("entity_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Country"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.ClimateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("climate_types");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.ClimateTypeWeatherType", b =>
                {
                    b.Property<int>("ClimateTypeId")
                        .HasColumnType("int")
                        .HasColumnName("climate_type_id");

                    b.Property<int>("WeatherTypeId")
                        .HasColumnType("int")
                        .HasColumnName("weather_type_id");

                    b.HasKey("ClimateTypeId", "WeatherTypeId");

                    b.HasIndex("WeatherTypeId");

                    b.ToTable("climate_type_weather_types", (string)null);
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("conferences");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int")
                        .HasColumnName("conference_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.ToTable("divisions");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.DivisionRotationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("division_id");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("int")
                        .HasColumnName("game_type_id");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("OponentDivisionId")
                        .HasColumnType("int")
                        .HasColumnName("oponent_division_id");

                    b.Property<int>("YearCycle")
                        .HasColumnType("int")
                        .HasColumnName("year_cycle");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("OponentDivisionId");

                    b.ToTable("division_rotation_schedules");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayTeamScore")
                        .HasColumnType("int")
                        .HasColumnName("away_team_score");

                    b.Property<int?>("FirstQuarterAwayScore")
                        .HasColumnType("int")
                        .HasColumnName("first_quarter_away_score");

                    b.Property<int?>("FirstQuarterHomeScore")
                        .HasColumnType("int")
                        .HasColumnName("first_quarter_home_score");

                    b.Property<int?>("FourthQuarterAwayScore")
                        .HasColumnType("int")
                        .HasColumnName("fourth_quarter_away_score");

                    b.Property<int?>("FourthQuarterHomeScore")
                        .HasColumnType("int")
                        .HasColumnName("fourth_quarter_home_score");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int?>("HomeTeamScore")
                        .HasColumnType("int")
                        .HasColumnName("home_team_score");

                    b.Property<int?>("Humidity")
                        .HasColumnType("int")
                        .HasColumnName("humidity");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("OvertimeAwayScore")
                        .HasColumnType("int")
                        .HasColumnName("overtime_away_score");

                    b.Property<int?>("OvertimeHomeScore")
                        .HasColumnType("int")
                        .HasColumnName("overtime_home_score");

                    b.Property<int>("SeasonScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("season_schedule_id");

                    b.Property<int?>("SecondQuarterAwayScore")
                        .HasColumnType("int")
                        .HasColumnName("second_quarter_away_score");

                    b.Property<int?>("SecondQuarterHomeScore")
                        .HasColumnType("int")
                        .HasColumnName("second_quarter_home_score");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("int")
                        .HasColumnName("stadium_id");

                    b.Property<bool>("StadiumRoofOpen")
                        .HasColumnType("bit")
                        .HasColumnName("stadium_roof_open");

                    b.Property<int?>("Temperature")
                        .HasColumnType("int")
                        .HasColumnName("temperature");

                    b.Property<int?>("ThirdQuarterAwayScore")
                        .HasColumnType("int")
                        .HasColumnName("third_quarter_away_score");

                    b.Property<int?>("ThirdQuarterHomeScore")
                        .HasColumnType("int")
                        .HasColumnName("third_quarter_home_score");

                    b.Property<int>("WeatherTypeId")
                        .HasColumnType("int")
                        .HasColumnName("weather_type_id");

                    b.Property<string>("WindDirection")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("wind_direction");

                    b.Property<int?>("WindSpeed")
                        .HasColumnType("int")
                        .HasColumnName("wind_speed");

                    b.HasKey("Id");

                    b.HasIndex("SeasonScheduleId");

                    b.HasIndex("StadiumId");

                    b.HasIndex("WeatherTypeId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.GameType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("game_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intraconference"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Interconference"
                        },
                        new
                        {
                            Id = 3,
                            Name = "17th Game"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.QualificationType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("qualification_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Division Champion"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WildCard"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.RankingScopeType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ranking_scope_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Division"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Conference"
                        },
                        new
                        {
                            Id = 3,
                            Name = "League"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "General User"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("begin_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("seasons");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonByeWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("SeasonWeekId")
                        .HasColumnType("int")
                        .HasColumnName("season_week_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("SeasonWeekId");

                    b.HasIndex("TeamId");

                    b.ToTable("season_bye_weeks");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int")
                        .HasColumnName("away_team_id");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int")
                        .HasColumnName("home_team_id");

                    b.Property<int>("WeekId")
                        .HasColumnType("int")
                        .HasColumnName("week_id");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("WeekId");

                    b.ToTable("season_schedules");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("season_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Preseason"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Regular Season"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Playoffs"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("begin_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("season_weeks");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archive")
                        .HasColumnType("bit")
                        .HasColumnName("archive");

                    b.Property<DateTime>("BrokeGround")
                        .HasColumnType("datetime2")
                        .HasColumnName("broke_ground");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<int>("ClimateTypeId")
                        .HasColumnType("int")
                        .HasColumnName("climate_type_id");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsInternationalMatchCandidate")
                        .HasColumnType("bit")
                        .HasColumnName("is_international_match_candidate");

                    b.Property<bool>("IsSuperBowlCandidate")
                        .HasColumnType("bit")
                        .HasColumnName("is_super_bowl_candidate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Opened")
                        .HasColumnType("datetime2")
                        .HasColumnName("opened");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("StadiumTypeId")
                        .HasColumnType("int")
                        .HasColumnName("stadium_type_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ClimateTypeId");

                    b.HasIndex("StadiumTypeId");

                    b.ToTable("stadiums");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.StadiumType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("stadium_types");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("abbreviation");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("Fips")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fips");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("states");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.StatisticGenerationMethodType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("statistic_generation_method_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Random"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Performance-Based"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archive")
                        .HasColumnType("bit")
                        .HasColumnName("archive");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("division_id");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int")
                        .HasColumnName("founded_year");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Mascot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("mascot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RankRandomizer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rank_randomizer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int")
                        .HasColumnName("stadium_id");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("StadiumId");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.TeamPostSeasonStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalculatedCoachRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("calculated_coach_rating");

                    b.Property<decimal>("CalculatedDefenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("calculated_defense_rating");

                    b.Property<decimal>("CalculatedOffenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("calculated_offense_rating");

                    b.Property<decimal>("CalculatedOverallRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("calculated_overall_rating");

                    b.Property<decimal>("CalculatedSpecialTeamsRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("calculated_special_teams_rating");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<decimal>("DraftBoostDefenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("draft_boost_defense_rating");

                    b.Property<decimal>("DraftBoostOffenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("draft_boost_offense_rating");

                    b.Property<int>("DraftPosition")
                        .HasColumnType("int")
                        .HasColumnName("draft_position");

                    b.Property<decimal>("DraftVariance")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("draft_variance");

                    b.Property<decimal>("FinalCoachRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("final_coach_rating");

                    b.Property<decimal>("FinalDefenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("final_defense_rating");

                    b.Property<decimal>("FinalHomeAdvantageRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("final_home_advantage_rating");

                    b.Property<decimal>("FinalOffenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("final_offense_rating");

                    b.Property<decimal>("FinalOverallRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("final_overall_rating");

                    b.Property<decimal>("FinalSpecialTeamsRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("final_special_teams_rating");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("HomeAdvantageRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("home_advantage_rating");

                    b.Property<decimal>("PlayoffCoachBonus")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("playoff_coach_bonus");

                    b.Property<decimal>("PlayoffDefenseBonus")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("playoff_defense_bonus");

                    b.Property<int>("PlayoffGamesPlayed")
                        .HasColumnType("int")
                        .HasColumnName("playoff_games_played");

                    b.Property<int>("PlayoffLosses")
                        .HasColumnType("int")
                        .HasColumnName("playoff_losses");

                    b.Property<decimal>("PlayoffOffenseBonus")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("playoff_offense_bonus");

                    b.Property<int>("PlayoffPointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("playoff_points_against");

                    b.Property<int>("PlayoffPointsFor")
                        .HasColumnType("int")
                        .HasColumnName("playoff_points_for");

                    b.Property<decimal>("PlayoffSpecialTeamsBonus")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("playoff_special_teams_bonus");

                    b.Property<int>("PlayoffWins")
                        .HasColumnType("int")
                        .HasColumnName("playoff_wins");

                    b.Property<decimal>("PreviousCoachRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("previous_coach_rating");

                    b.Property<decimal>("PreviousDefenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("previous_defense_rating");

                    b.Property<int>("PreviousFinalLeagueRank")
                        .HasColumnType("int")
                        .HasColumnName("previous_final_league_rank");

                    b.Property<decimal>("PreviousHomeAdvantageRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("previous_home_advantage_rating");

                    b.Property<decimal>("PreviousHomeWinPercentage")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("previous_home_win_percentage");

                    b.Property<decimal>("PreviousOffenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("previous_offense_rating");

                    b.Property<decimal>("PreviousOverallRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("previous_overall_rating");

                    b.Property<int>("PreviousPointDifferential")
                        .HasColumnType("int")
                        .HasColumnName("previous_point_differential");

                    b.Property<int>("PreviousPostSeasonId")
                        .HasColumnType("int")
                        .HasColumnName("previous_post_season_id");

                    b.Property<int>("PreviousRegularSesasonId")
                        .HasColumnType("int")
                        .HasColumnName("previous_regular_sesason_id");

                    b.Property<decimal>("PreviousSpecialTeamsRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("previous_special_teams_rating");

                    b.Property<int>("PreviousTotalPointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("previous_total_points_against");

                    b.Property<int>("PreviousTotalPointsFor")
                        .HasColumnType("int")
                        .HasColumnName("previous_total_points_for");

                    b.Property<decimal>("PreviousWinPercentage")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("previous_win_percentage");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<int>("StatisticGenerationMethodTypeId")
                        .HasColumnType("int")
                        .HasColumnName("statistic_generation_method_type_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<decimal>("UpsetBonusTotal")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("upset_bonus_total");

                    b.Property<int>("UpsetWins")
                        .HasColumnType("int")
                        .HasColumnName("upset_wins");

                    b.HasKey("Id");

                    b.HasIndex("PreviousPostSeasonId");

                    b.HasIndex("PreviousRegularSesasonId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StatisticGenerationMethodTypeId");

                    b.HasIndex("TeamId");

                    b.ToTable("team_post_season_statistics");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.TeamRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoachingRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("coaching_rating");

                    b.Property<decimal>("DefenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("defense_rating");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("HomeFieldAdvantageRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("home_field_advantage_rating");

                    b.Property<decimal>("OffenseRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("offense_rating");

                    b.Property<decimal>("OverallRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("overall_rating");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<decimal>("SpecialTeamsRating")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("special_teams_rating");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("team_ratings");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.TeamSeasonStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceLosses")
                        .HasColumnType("int")
                        .HasColumnName("conference_losses");

                    b.Property<int>("ConferenceRank")
                        .HasColumnType("int")
                        .HasColumnName("conference_rank");

                    b.Property<int>("ConferenceSeeding")
                        .HasColumnType("int")
                        .HasColumnName("conference_seeding");

                    b.Property<int>("ConferenceTies")
                        .HasColumnType("int")
                        .HasColumnName("conference_ties");

                    b.Property<decimal>("ConferenceWinPercentage")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("conference_win_percentage");

                    b.Property<int>("ConferenceWins")
                        .HasColumnType("int")
                        .HasColumnName("conference_wins");

                    b.Property<int>("DivisionLosses")
                        .HasColumnType("int")
                        .HasColumnName("division_losses");

                    b.Property<decimal>("DivisionRank")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("division_rank");

                    b.Property<int>("DivisionTies")
                        .HasColumnType("int")
                        .HasColumnName("division_ties");

                    b.Property<decimal>("DivisionWinPercentage")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("division_win_percentage");

                    b.Property<int>("DivisionWins")
                        .HasColumnType("int")
                        .HasColumnName("division_wins");

                    b.Property<int>("FinalLeagueRank")
                        .HasColumnType("int")
                        .HasColumnName("final_league_rank");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("HomeGames")
                        .HasColumnType("int")
                        .HasColumnName("home_games");

                    b.Property<decimal>("HomeWinPercentage")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("home_win_percentage");

                    b.Property<int>("HomeWins")
                        .HasColumnType("int")
                        .HasColumnName("home_wins");

                    b.Property<int>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<int>("PointDifferential")
                        .HasColumnType("int")
                        .HasColumnName("point_differential");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("points_against");

                    b.Property<int>("PointsFor")
                        .HasColumnType("int")
                        .HasColumnName("points_for");

                    b.Property<int>("PostSeasonId")
                        .HasColumnType("int")
                        .HasColumnName("post_season_id");

                    b.Property<int?>("QualificationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("qualification_type_id");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<decimal>("StrengthOfSchedule")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("strength_of_schedule");

                    b.Property<decimal>("StrengthOfVictory")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("strength_of_victory");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int>("Ties")
                        .HasColumnType("int")
                        .HasColumnName("ties");

                    b.Property<decimal>("WinPercentage")
                        .HasColumnType("decimal(6, 5)")
                        .HasColumnName("win_percentage");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("PostSeasonId");

                    b.HasIndex("QualificationTypeId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("team_season_statistics");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("application_user_id");

                    b.Property<bool>("Archive")
                        .HasColumnType("bit")
                        .HasColumnName("archive");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.UserLoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.HasKey("Id");

                    b.ToTable("user_login_histories");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.WeatherType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("weather_types");
                });

            modelBuilder.Entity("FootballSimulator.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Common.Core.Domain.EntityHistory", b =>
                {
                    b.HasOne("Common.Core.Domain.EntityType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Common.Core.Domain.UserCommandEvent", "Event", b1 =>
                        {
                            b1.Property<long>("EntityHistoryId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("Date")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasColumnName("date")
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("user_id");

                            b1.HasKey("EntityHistoryId");

                            b1.HasIndex("UserId");

                            b1.ToTable("entity_histories");

                            b1.WithOwner()
                                .HasForeignKey("EntityHistoryId");

                            b1.HasOne("FootballSimulator.Core.Domain.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.Navigation("Event")
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Common.Core.Domain.EntityHistoryChange", b =>
                {
                    b.HasOne("Common.Core.Domain.EntityHistory", "EntityHistory")
                        .WithMany("Changes")
                        .HasForeignKey("EntityHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Common.Core.Domain.EntityChange", "Change", b1 =>
                        {
                            b1.Property<long>("EntityHistoryChangeId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("description");

                            b1.Property<string>("NewValue")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("new_value");

                            b1.Property<string>("OldValue")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("old_value");

                            b1.HasKey("EntityHistoryChangeId");

                            b1.ToTable("entity_history_changes");

                            b1.WithOwner()
                                .HasForeignKey("EntityHistoryChangeId");
                        });

                    b.OwnsOne("Common.Core.Domain.EntityProperty", "Property", b1 =>
                        {
                            b1.Property<long>("EntityHistoryChangeId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FriendlyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("friendly_name");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("type");

                            b1.HasKey("EntityHistoryChangeId");

                            b1.ToTable("entity_history_changes");

                            b1.WithOwner()
                                .HasForeignKey("EntityHistoryChangeId");
                        });

                    b.Navigation("Change")
                        .IsRequired();

                    b.Navigation("EntityHistory");

                    b.Navigation("Property")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.City", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.ClimateTypeWeatherType", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.ClimateType", "ClimateType")
                        .WithMany("ClimateTypeWeatherTypes")
                        .HasForeignKey("ClimateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.WeatherType", "WeatherType")
                        .WithMany("ClimateTypeWeatherTypes")
                        .HasForeignKey("WeatherTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateType");

                    b.Navigation("WeatherType");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Division", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Conference", "Conference")
                        .WithMany("Divisions")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.DivisionRotationSchedule", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Division", "OponentDivision")
                        .WithMany()
                        .HasForeignKey("OponentDivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("GameType");

                    b.Navigation("OponentDivision");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Game", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.SeasonSchedule", "SeasonSchedule")
                        .WithMany("Games")
                        .HasForeignKey("SeasonScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballSimulator.Core.Domain.WeatherType", "WeatherType")
                        .WithMany()
                        .HasForeignKey("WeatherTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SeasonSchedule");

                    b.Navigation("Stadium");

                    b.Navigation("WeatherType");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Season", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.SeasonType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonByeWeek", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.SeasonWeek", "SeasonWeek")
                        .WithMany("SeasonByeWeeks")
                        .HasForeignKey("SeasonWeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Team", "Team")
                        .WithMany("SeasonByeWeeks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SeasonWeek");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonSchedule", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.SeasonWeek", "SeasonWeek")
                        .WithMany("SeasonSchedules")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("SeasonWeek");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonWeek", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Season", "Season")
                        .WithMany("Weeks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Stadium", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.ClimateType", "ClimateType")
                        .WithMany()
                        .HasForeignKey("ClimateTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.StadiumType", "StadiumType")
                        .WithMany()
                        .HasForeignKey("StadiumTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Common.Core.Domain.ChangeEvents", "ChangeEvents", b1 =>
                        {
                            b1.Property<int>("StadiumId")
                                .HasColumnType("int");

                            b1.HasKey("StadiumId");

                            b1.ToTable("stadiums");

                            b1.WithOwner()
                                .HasForeignKey("StadiumId");

                            b1.OwnsOne("Common.Core.Domain.UserCommandEvent", "Created", b2 =>
                                {
                                    b2.Property<int>("ChangeEventsStadiumId")
                                        .HasColumnType("int");

                                    b2.Property<DateTime>("Date")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("datetime2")
                                        .HasColumnName("created_date")
                                        .HasDefaultValueSql("GETUTCDATE()");

                                    b2.Property<int>("UserId")
                                        .HasColumnType("int")
                                        .HasColumnName("created_user_id");

                                    b2.HasKey("ChangeEventsStadiumId");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("stadiums");

                                    b2.WithOwner()
                                        .HasForeignKey("ChangeEventsStadiumId");

                                    b2.HasOne("FootballSimulator.Core.Domain.User", "User")
                                        .WithMany()
                                        .HasForeignKey("UserId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired();

                                    b2.Navigation("User");
                                });

                            b1.OwnsOne("Common.Core.Domain.UserCommandEvent", "Updated", b2 =>
                                {
                                    b2.Property<int>("ChangeEventsStadiumId")
                                        .HasColumnType("int");

                                    b2.Property<DateTime>("Date")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("datetime2")
                                        .HasColumnName("updated_date")
                                        .HasDefaultValueSql("GETUTCDATE()");

                                    b2.Property<int>("UserId")
                                        .HasColumnType("int")
                                        .HasColumnName("updated_user_id");

                                    b2.HasKey("ChangeEventsStadiumId");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("stadiums");

                                    b2.WithOwner()
                                        .HasForeignKey("ChangeEventsStadiumId");

                                    b2.HasOne("FootballSimulator.Core.Domain.User", "User")
                                        .WithMany()
                                        .HasForeignKey("UserId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired();

                                    b2.Navigation("User");
                                });

                            b1.Navigation("Created")
                                .IsRequired();

                            b1.Navigation("Updated")
                                .IsRequired();
                        });

                    b.Navigation("ChangeEvents")
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("ClimateType");

                    b.Navigation("StadiumType");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.State", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Team", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Division", "Division")
                        .WithMany("Teams")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Stadium", "Stadium")
                        .WithMany("Teams")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Common.Core.Domain.ChangeEvents", "ChangeEvents", b1 =>
                        {
                            b1.Property<int>("TeamId")
                                .HasColumnType("int");

                            b1.HasKey("TeamId");

                            b1.ToTable("teams");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");

                            b1.OwnsOne("Common.Core.Domain.UserCommandEvent", "Created", b2 =>
                                {
                                    b2.Property<int>("ChangeEventsTeamId")
                                        .HasColumnType("int");

                                    b2.Property<DateTime>("Date")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("datetime2")
                                        .HasColumnName("created_date")
                                        .HasDefaultValueSql("GETUTCDATE()");

                                    b2.Property<int>("UserId")
                                        .HasColumnType("int")
                                        .HasColumnName("created_user_id");

                                    b2.HasKey("ChangeEventsTeamId");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("teams");

                                    b2.WithOwner()
                                        .HasForeignKey("ChangeEventsTeamId");

                                    b2.HasOne("FootballSimulator.Core.Domain.User", "User")
                                        .WithMany()
                                        .HasForeignKey("UserId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired();

                                    b2.Navigation("User");
                                });

                            b1.OwnsOne("Common.Core.Domain.UserCommandEvent", "Updated", b2 =>
                                {
                                    b2.Property<int>("ChangeEventsTeamId")
                                        .HasColumnType("int");

                                    b2.Property<DateTime>("Date")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("datetime2")
                                        .HasColumnName("updated_date")
                                        .HasDefaultValueSql("GETUTCDATE()");

                                    b2.Property<int>("UserId")
                                        .HasColumnType("int")
                                        .HasColumnName("updated_user_id");

                                    b2.HasKey("ChangeEventsTeamId");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("teams");

                                    b2.WithOwner()
                                        .HasForeignKey("ChangeEventsTeamId");

                                    b2.HasOne("FootballSimulator.Core.Domain.User", "User")
                                        .WithMany()
                                        .HasForeignKey("UserId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired();

                                    b2.Navigation("User");
                                });

                            b1.Navigation("Created")
                                .IsRequired();

                            b1.Navigation("Updated")
                                .IsRequired();
                        });

                    b.Navigation("ChangeEvents")
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.TeamPostSeasonStatistic", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Season", "PreviousPostSeason")
                        .WithMany()
                        .HasForeignKey("PreviousPostSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Season", "PreviousRegularSeason")
                        .WithMany()
                        .HasForeignKey("PreviousRegularSesasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.StatisticGenerationMethodType", "StatisticGenerationMethodType")
                        .WithMany()
                        .HasForeignKey("StatisticGenerationMethodTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Team", "Team")
                        .WithMany("TeamPostSeasonStatistics")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PreviousPostSeason");

                    b.Navigation("PreviousRegularSeason");

                    b.Navigation("Season");

                    b.Navigation("StatisticGenerationMethodType");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.TeamRating", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Team", "Team")
                        .WithMany("TeamRatings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.TeamSeasonStatistic", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Season", "PostSeason")
                        .WithMany()
                        .HasForeignKey("PostSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.QualificationType", "QualificationType")
                        .WithMany()
                        .HasForeignKey("QualificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballSimulator.Core.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.Team", "Team")
                        .WithMany("TeamSeasonStatistics")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostSeason");

                    b.Navigation("QualificationType");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.User", b =>
                {
                    b.HasOne("FootballSimulator.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Common.Core.Domain.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.UserLoginHistory", b =>
                {
                    b.OwnsOne("Common.Core.Domain.UserCommandEvent", "Event", b1 =>
                        {
                            b1.Property<int>("UserLoginHistoryId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Date")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasColumnName("date")
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("user_id");

                            b1.HasKey("UserLoginHistoryId");

                            b1.HasIndex("UserId");

                            b1.ToTable("user_login_histories");

                            b1.HasOne("FootballSimulator.Core.Domain.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserLoginHistoryId");

                            b1.Navigation("User");
                        });

                    b.Navigation("Event")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.UserRole", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FootballSimulator.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FootballSimulator.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FootballSimulator.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Core.Domain.EntityHistory", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.ClimateType", b =>
                {
                    b.Navigation("ClimateTypeWeatherTypes");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Conference", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Division", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Season", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonSchedule", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.SeasonWeek", b =>
                {
                    b.Navigation("SeasonByeWeeks");

                    b.Navigation("SeasonSchedules");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Stadium", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Team", b =>
                {
                    b.Navigation("SeasonByeWeeks");

                    b.Navigation("TeamPostSeasonStatistics");

                    b.Navigation("TeamRatings");

                    b.Navigation("TeamSeasonStatistics");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.WeatherType", b =>
                {
                    b.Navigation("ClimateTypeWeatherTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
