// <auto-generated />
using System;
using FootballSimulator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballSimulator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FootballSimulatorDbContext))]
    partial class FootballSimulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Core.Domain.EntityHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CommandTypeId")
                        .HasColumnType("int")
                        .HasColumnName("command_type_id");

                    b.Property<Guid>("EntityGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_guid");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("entity_histories");
                });

            modelBuilder.Entity("Common.Core.Domain.EntityHistoryChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityHistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_history_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityHistoryId");

                    b.ToTable("entity_history_changes");
                });

            modelBuilder.Entity("Common.Core.Domain.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("entity_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Country"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "General User"
                        });
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archive")
                        .HasColumnType("bit")
                        .HasColumnName("archive");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.UserLoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.HasKey("Id");

                    b.ToTable("user_login_histories");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("FootballSimulator.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("application_users", (string)null);
                });

            modelBuilder.Entity("Common.Core.Domain.EntityHistory", b =>
                {
                    b.HasOne("Common.Core.Domain.EntityType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Common.Core.Domain.UserCommandEvent", "Event", b1 =>
                        {
                            b1.Property<long>("EntityHistoryId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("Date")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasColumnName("date")
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("user_id");

                            b1.HasKey("EntityHistoryId");

                            b1.HasIndex("UserId");

                            b1.ToTable("entity_histories");

                            b1.WithOwner()
                                .HasForeignKey("EntityHistoryId");

                            b1.HasOne("FootballSimulator.Core.Domain.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.Navigation("Event")
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Common.Core.Domain.EntityHistoryChange", b =>
                {
                    b.HasOne("Common.Core.Domain.EntityHistory", "EntityHistory")
                        .WithMany("Changes")
                        .HasForeignKey("EntityHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Common.Core.Domain.EntityChange", "Change", b1 =>
                        {
                            b1.Property<long>("EntityHistoryChangeId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("description");

                            b1.Property<string>("NewValue")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("new_value");

                            b1.Property<string>("OldValue")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("old_value");

                            b1.HasKey("EntityHistoryChangeId");

                            b1.ToTable("entity_history_changes");

                            b1.WithOwner()
                                .HasForeignKey("EntityHistoryChangeId");
                        });

                    b.OwnsOne("Common.Core.Domain.EntityProperty", "Property", b1 =>
                        {
                            b1.Property<long>("EntityHistoryChangeId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FriendlyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("friendly_name");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("type");

                            b1.HasKey("EntityHistoryChangeId");

                            b1.ToTable("entity_history_changes");

                            b1.WithOwner()
                                .HasForeignKey("EntityHistoryChangeId");
                        });

                    b.Navigation("Change")
                        .IsRequired();

                    b.Navigation("EntityHistory");

                    b.Navigation("Property")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.User", b =>
                {
                    b.OwnsOne("Common.Core.Domain.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.UserLoginHistory", b =>
                {
                    b.OwnsOne("Common.Core.Domain.UserCommandEvent", "Event", b1 =>
                        {
                            b1.Property<int>("UserLoginHistoryId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Date")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime2")
                                .HasColumnName("date")
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("user_id");

                            b1.HasKey("UserLoginHistoryId");

                            b1.HasIndex("UserId");

                            b1.ToTable("user_login_histories");

                            b1.HasOne("FootballSimulator.Core.Domain.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserLoginHistoryId");

                            b1.Navigation("User");
                        });

                    b.Navigation("Event")
                        .IsRequired();
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.UserRole", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballSimulator.Core.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballSimulator.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.HasOne("FootballSimulator.Core.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("FootballSimulator.Infrastructure.Data.ApplicationUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.Core.Domain.EntityHistory", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("FootballSimulator.Core.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
