using Common.Core.Domain;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace Common.Core
{
    public sealed partial class FileExtensions : ReadOnlyDictionary<string, FileExtension>
    {
        /// <summary>
        /// List of known (800+) file extension and MIME types.
        /// NOTE: Adding any file extensions to the list will impact any exisiting applications using this class
        ///       that may update to a later version. This list is meant to be a starting point only and should be considered immutable.
        ///       If a particular application needs a custom file extension, pass extension into the constructor from the calling application.
        ///       Please document and assess existing applications prior to adding any new extensions to this default list.
        /// Signatures: https://www.filesignatures.net/index.php?page=all
        /// </summary>
        public static IReadOnlyDictionary<string, FileExtension> DefaultExtensions = new List<FileExtension>()
        {
            new FileExtension("323","text/h323"),
            new FileExtension("123","application/vnd.lotus-1-2-3"),
            new FileExtension("3dml","text/vnd.in3d.3dml"),
            new FileExtension("3g2","video/3gpp2"),
            new FileExtension("3gp","video/3gpp"),
            new FileExtension("7z","application/x-7z-compressed"),
            new FileExtension("aab","application/x-authorware-bin"),
            new FileExtension("aac","audio/x-aac"),
            new FileExtension("aam","application/x-authorware-map"),
            new FileExtension("aas","application/x-authorware-seg"),
            new FileExtension("abw","application/x-abiword"),
            new FileExtension("ac","application/pkix-attr-cert"),
            new FileExtension("acc","application/vnd.americandynamics.acc"),
            new FileExtension("ace","application/x-ace-compressed"),
            new FileExtension("acu","application/vnd.acucobol"),
            new FileExtension("acx","application/internet-property-stream"),
            new FileExtension("adp","audio/adpcm"),
            new FileExtension("aep","application/vnd.audiograph"),
            new FileExtension("afp","application/vnd.ibm.modcap"),
            new FileExtension("ahead","application/vnd.ahead.space"),
            new FileExtension("ai","application/postscript"),
            new FileExtension("aif","audio/x-aiff"),
            new FileExtension("aifc","audio/x-aiff"),
            new FileExtension("aiff","audio/x-aiff"),
            new FileExtension("air","application/vnd.adobe.air-application-installer-package+zip"),
            new FileExtension("ait","application/vnd.dvb.ait"),
            new FileExtension("ami","application/vnd.amiga.ami"),
            new FileExtension("apk","application/vnd.android.package-archive"),
            new FileExtension("application","application/x-ms-application"),
            new FileExtension("apr","application/vnd.lotus-approach"),
            new FileExtension("arc","application/x-freearc"),
            new FileExtension("asc","text/plain"),
            new FileExtension("asf","video/x-ms-asf"),
            new FileExtension("aso","application/vnd.accpac.simply.aso"),
            new FileExtension("asr","video/x-ms-asf"),
            new FileExtension("asx","video/x-ms-asf"),
            new FileExtension("atc","application/vnd.acucorp"),
            new FileExtension("atom","application/atom+xml"),
            new FileExtension("atomcat","application/atomcat+xml"),
            new FileExtension("atomsvc","application/atomsvc+xml"),
            new FileExtension("atx","application/vnd.antix.game-component"),
            new FileExtension("au","audio/basic",
                new List<byte[]> 
                { 
                    new byte[] { 0x64, 0x6E, 0x73, 0x2E },
                    new byte[] { 0x2E, 0x73, 0x6E, 0x64 }
                }),
            new FileExtension("avi","video/x-msvideo"),
            new FileExtension("aw","application/applixware"),
            new FileExtension("axs","application/olescript"),
            new FileExtension("azf","application/vnd.airzip.filesecure.azf"),
            new FileExtension("azs","application/vnd.airzip.filesecure.azs"),
            new FileExtension("azw","application/vnd.amazon.ebook"),
            new FileExtension("bas","text/plain"),
            new FileExtension("bcpio","application/x-bcpio"),
            new FileExtension("bdf","application/x-font-bdf"),
            new FileExtension("bdm","application/vnd.syncml.dm+wbxml"),
            new FileExtension("bed","application/vnd.realvnc.bed"),
            new FileExtension("bh2","application/vnd.fujitsu.oasysprs"),
            new FileExtension("bin","application/octet-stream"),
            new FileExtension("bmi","application/vnd.bmi"),
            new FileExtension("bmp","image/bmp",
                new List<byte[]> { new byte[] { 0x42, 0x4D } }),
            new FileExtension("box","application/vnd.previewsystems.box"),
            new FileExtension("btif","image/prs.btif"),
            new FileExtension("bz","application/x-bzip"),
            new FileExtension("bz2","application/x-bzip2"),
            new FileExtension("c","text/x-c"),
            new FileExtension("c11amc","application/vnd.cluetrust.cartomobile-config"),
            new FileExtension("c11amz","application/vnd.cluetrust.cartomobile-config-pkg"),
            new FileExtension("c4g","application/vnd.clonk.c4group"),
            new FileExtension("cab","application/vnd.ms-cab-compressed"),
            new FileExtension("car","application/vnd.curl.car"),
            new FileExtension("cat","application/vnd.ms-pki.seccat"),
            new FileExtension("ccxml","application/ccxml+xml,"),
            new FileExtension("cdbcmsg","application/vnd.contact.cmsg"),
            new FileExtension("cdf","application/x-cdf"),
            new FileExtension("cdkey","application/vnd.mediastation.cdkey"),
            new FileExtension("cdmia","application/cdmi-capability"),
            new FileExtension("cdmic","application/cdmi-container"),
            new FileExtension("cdmid","application/cdmi-domain"),
            new FileExtension("cdmio","application/cdmi-object"),
            new FileExtension("cdmiq","application/cdmi-queue"),
            new FileExtension("cdx","chemical/x-cdx"),
            new FileExtension("cdxml","application/vnd.chemdraw+xml"),
            new FileExtension("cdy","application/vnd.cinderella"),
            new FileExtension("cer","application/pkix-cert"),
            new FileExtension("cgm","image/cgm"),
            new FileExtension("chat","application/x-chat"),
            new FileExtension("chm","application/vnd.ms-htmlhelp"),
            new FileExtension("chrt","application/vnd.kde.kchart"),
            new FileExtension("cif","chemical/x-cif"),
            new FileExtension("cii","application/vnd.anser-web-certificate-issue-initiation"),
            new FileExtension("cil","application/vnd.ms-artgalry"),
            new FileExtension("cla","application/vnd.claymore"),
            new FileExtension("class","application/java-vm"),
            new FileExtension("clkk","application/vnd.crick.clicker.keyboard"),
            new FileExtension("clkp","application/vnd.crick.clicker.palette"),
            new FileExtension("clkt","application/vnd.crick.clicker.template"),
            new FileExtension("clkw","application/vnd.crick.clicker.wordbank"),
            new FileExtension("clkx","application/vnd.crick.clicker"),
            new FileExtension("clp","application/x-msclip"),
            new FileExtension("cmc","application/vnd.cosmocaller"),
            new FileExtension("cmdf","chemical/x-cmdf"),
            new FileExtension("cml","chemical/x-cml"),
            new FileExtension("cmp","application/vnd.yellowriver-custom-menu"),
            new FileExtension("cmx","image/x-cmx"),
            new FileExtension("cod","image/cis-cod"),
            new FileExtension("cpio","application/x-cpio"),
            new FileExtension("cpt","application/mac-compactpro"),
            new FileExtension("crd","application/x-mscardfile"),
            new FileExtension("crl","application/pkix-crl"),
            new FileExtension("crt","application/x-x509-ca-cert"),
            new FileExtension("cryptonote","application/vnd.rig.cryptonote"),
            new FileExtension("csh","application/x-csh"),
            new FileExtension("csml","chemical/x-csml"),
            new FileExtension("csp","application/vnd.commonspace"),
            new FileExtension("css","text/css"),
            new FileExtension("csv","text/csv"),
            new FileExtension("cu","application/cu-seeme"),
            new FileExtension("curl","text/vnd.curl"),
            new FileExtension("cww","application/prs.cww"),
            new FileExtension("dae","model/vnd.collada+xml"),
            new FileExtension("daf","application/vnd.mobius.daf"),
            new FileExtension("davmount","application/davmount+xml"),
            new FileExtension("dcr","application/x-director"),
            new FileExtension("dcurl","text/vnd.curl.dcurl"),
            new FileExtension("dd2","application/vnd.oma.dd2+xml"),
            new FileExtension("ddd","application/vnd.fujixerox.ddd"),
            new FileExtension("deb","application/x-debian-package"),
            new FileExtension("der","application/x-x509-ca-cert"),
            new FileExtension("dfac","application/vnd.dreamfactory"),
            new FileExtension("dif","video/x-dv"),
            new FileExtension("dir","application/x-director"),
            new FileExtension("dis","application/vnd.mobius.dis"),
            new FileExtension("djv","image/vnd.djvu"),
            new FileExtension("djvu","image/vnd.djvu"),
            new FileExtension("dll","application/x-msdownload"),
            new FileExtension("dmg","application/x-apple-diskimage"),
            new FileExtension("dms","application/octet-stream"),
            new FileExtension("dna","application/vnd.dna"),
            new FileExtension("doc","application/msword", 
                new List<byte[]> { new byte[] { 0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1 } }),
            new FileExtension("docm","application/vnd.ms-word.document.macroEnabled.12"),
            new FileExtension("docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                new List<byte[]> { new byte[] { 0x50, 0x4B, 0x03, 0x04 } }),
            new FileExtension("dot","application/msword"),
            new FileExtension("dotm","application/vnd.ms-word.template.macroEnabled.12"),
            new FileExtension("dotx","application/vnd.openxmlformats-officedocument.wordprocessingml.template"),
            new FileExtension("dp","application/vnd.osgi.dp"),
            new FileExtension("dpg","application/vnd.dpgraph"),
            new FileExtension("dra","audio/vnd.dra"),
            new FileExtension("dsc","text/prs.lines.tag"),
            new FileExtension("dssc","application/dssc+der"),
            new FileExtension("dtb","application/x-dtbook+xml"),
            new FileExtension("dtd","application/xml-dtd"),
            new FileExtension("dts","audio/vnd.dts"),
            new FileExtension("dtshd","audio/vnd.dts.hd"),
            new FileExtension("dv","video/x-dv"),
            new FileExtension("dvi","application/x-dvi"),
            new FileExtension("dwf","model/vnd.dwf"),
            new FileExtension("dwg","image/vnd.dwg"),
            new FileExtension("dxf","image/vnd.dxf"),
            new FileExtension("dxp","application/vnd.spotfire.dxp"),
            new FileExtension("dxr","application/x-director"),
            new FileExtension("ecelp4800","audio/vnd.nuera.ecelp4800"),
            new FileExtension("ecelp7470","audio/vnd.nuera.ecelp7470"),
            new FileExtension("ecelp9600","audio/vnd.nuera.ecelp9600"),
            new FileExtension("edm","application/vnd.novadigm.edm"),
            new FileExtension("edx","application/vnd.novadigm.edx"),
            new FileExtension("efif","application/vnd.picsel"),
            new FileExtension("ei6","application/vnd.pg.osasli"),
            new FileExtension("eml","message/rfc822"),
            new FileExtension("emma","application/emma+xml"),
            new FileExtension("eol","audio/vnd.digital-winds"),
            new FileExtension("eot","application/vnd.ms-fontobject"),
            new FileExtension("eps","application/postscript"),
            new FileExtension("epub","application/epub+zip"),
            new FileExtension("es","application/ecmascript"),
            new FileExtension("es3","application/vnd.eszigno3+xml"),
            new FileExtension("esf","application/vnd.epson.esf"),
            new FileExtension("etx","text/x-setext"),
            new FileExtension("evy","application/envoy"),
            new FileExtension("exe","application/x-msdownload"),
            new FileExtension("exi","application/exi"),
            new FileExtension("ext","application/vnd.novadigm.ext"),
            new FileExtension("ez","application/andrew-inset"),
            new FileExtension("ez2","application/vnd.ezpix-album"),
            new FileExtension("ez3","application/vnd.ezpix-package"),
            new FileExtension("f","text/x-fortran"),
            new FileExtension("f4v","video/x-f4v"),
            new FileExtension("fbs","image/vnd.fastbidsheet"),
            new FileExtension("fcs","application/vnd.isac.fcs"),
            new FileExtension("fdf","application/vnd.fdf"),
            new FileExtension("fe_launch","application/vnd.denovo.fcselayout-link"),
            new FileExtension("fg5","application/vnd.fujitsu.oasysgp"),
            new FileExtension("fh","image/x-freehand"),
            new FileExtension("fif","application/fractals"),
            new FileExtension("fig","application/x-xfig"),
            new FileExtension("fli","video/x-fli"),
            new FileExtension("flo","application/vnd.micrografx.flo"),
            new FileExtension("flr","x-world/x-vrml"),
            new FileExtension("flv","video/x-flv"),
            new FileExtension("flw","application/vnd.kde.kivio"),
            new FileExtension("flx","text/vnd.fmi.flexstor"),
            new FileExtension("fly","text/vnd.fly"),
            new FileExtension("fm","application/vnd.framemaker"),
            new FileExtension("fnc","application/vnd.frogans.fnc"),
            new FileExtension("fpx","image/vnd.fpx"),
            new FileExtension("fsc","application/vnd.fsc.weblaunch"),
            new FileExtension("fst","image/vnd.fst"),
            new FileExtension("ftc","application/vnd.fluxtime.clip"),
            new FileExtension("fti","application/vnd.anser-web-funds-transfer-initiation"),
            new FileExtension("fvt","video/vnd.fvt"),
            new FileExtension("fxp","application/vnd.adobe.fxp"),
            new FileExtension("fzs","application/vnd.fuzzysheet"),
            new FileExtension("g2w","application/vnd.geoplan"),
            new FileExtension("g3","image/g3fax"),
            new FileExtension("g3w","application/vnd.geospace"),
            new FileExtension("gac","application/vnd.groove-account"),
            new FileExtension("gdl","model/vnd.gdl"),
            new FileExtension("geo","application/vnd.dynageo"),
            new FileExtension("gex","application/vnd.geometry-explorer"),
            new FileExtension("ggb","application/vnd.geogebra.file"),
            new FileExtension("ggt","application/vnd.geogebra.tool"),
            new FileExtension("ghf","application/vnd.groove-help"),
            new FileExtension("gif","image/gif",
                new List<byte[]> { new byte[] { 0x47, 0x49, 0x46, 0x38 } }),
            new FileExtension("gim","application/vnd.groove-identity-message"),
            new FileExtension("gmx","application/vnd.gmx"),
            new FileExtension("gnumeric","application/x-gnumeric"),
            new FileExtension("gph","application/vnd.flographit"),
            new FileExtension("gqf","application/vnd.grafeq"),
            new FileExtension("gram","application/srgs"),
            new FileExtension("grv","application/vnd.groove-injector"),
            new FileExtension("grxml","application/srgs+xml"),
            new FileExtension("gsf","application/x-font-ghostscript"),
            new FileExtension("gtar","application/x-gtar"),
            new FileExtension("gtm","application/vnd.groove-tool-message"),
            new FileExtension("gtw","model/vnd.gtw"),
            new FileExtension("gv","text/vnd.graphviz"),
            new FileExtension("gxt","application/vnd.geonext"),
            new FileExtension("gz","application/gzip"),
            new FileExtension("h","text/plain"),
            new FileExtension("h261","video/h261"),
            new FileExtension("h263","video/h263"),
            new FileExtension("h264","video/h264"),
            new FileExtension("hal","application/vnd.hal+xml"),
            new FileExtension("hbci","application/vnd.hbci"),
            new FileExtension("hdf","application/x-hdf"),
            new FileExtension("hlp","application/winhlp"),
            new FileExtension("hpgl","application/vnd.hp-hpgl"),
            new FileExtension("hpid","application/vnd.hp-hpid"),
            new FileExtension("hps","application/vnd.hp-hps"),
            new FileExtension("hqx","application/mac-binhex40"),
            new FileExtension("hta","application/hta"),
            new FileExtension("htc","text/x-component"),
            new FileExtension("htke","application/vnd.kenameaapp"),
            new FileExtension("htm","text/html"),
            new FileExtension("html","text/html"),
            new FileExtension("htt","text/webviewhtml"),
            new FileExtension("hvd","application/vnd.yamaha.hv-dic"),
            new FileExtension("hvp","application/vnd.yamaha.hv-voice"),
            new FileExtension("hvs","application/vnd.yamaha.hv-script"),
            new FileExtension("i2g","application/vnd.intergeo"),
            new FileExtension("icc","application/vnd.iccprofile"),
            new FileExtension("ice","x-conference/x-cooltalk"),
            new FileExtension("ico","image/x-icon"),
            new FileExtension("ics","text/calendar"),
            new FileExtension("ief","image/ief"),
            new FileExtension("ifb","text/calendar"),
            new FileExtension("ifm","application/vnd.shana.informed.formdata"),
            new FileExtension("iges","model/iges"),
            new FileExtension("igl","application/vnd.igloader"),
            new FileExtension("igm","application/vnd.insors.igm"),
            new FileExtension("igs","model/iges"),
            new FileExtension("igx","application/vnd.micrografx.igx"),
            new FileExtension("iif","application/vnd.shana.informed.interchange"),
            new FileExtension("iii","application/x-iphone"),
            new FileExtension("imp","application/vnd.accpac.simply.imp"),
            new FileExtension("ims","application/vnd.ms-ims"),
            new FileExtension("ins","application/x-internet-signup"),
            new FileExtension("ipfix","application/ipfix"),
            new FileExtension("ipk","application/vnd.shana.informed.package"),
            new FileExtension("irm","application/vnd.ibm.rights-management"),
            new FileExtension("irp","application/vnd.irepository.package+xml"),
            new FileExtension("isp","application/x-internet-signup"),
            new FileExtension("itp","application/vnd.shana.informed.formtemplate"),
            new FileExtension("ivp","application/vnd.immervision-ivp"),
            new FileExtension("ivu","application/vnd.immervision-ivu"),
            new FileExtension("jad","text/vnd.sun.j2me.app-descriptor"),
            new FileExtension("jam","application/vnd.jam"),
            new FileExtension("jar","application/java-archive"),
            new FileExtension("java","text/x-java-source,java"),
            new FileExtension("jfif","image/pipeg"),
            new FileExtension("jisp","application/vnd.jisp"),
            new FileExtension("jlt","application/vnd.hp-jlyt"),
            new FileExtension("jnlp","application/x-java-jnlp-file"),
            new FileExtension("joda","application/vnd.joost.joda-archive"),
            new FileExtension("jp2","image/jp2"),
            new FileExtension("jpe","image/jpeg"),
            new FileExtension("jpeg","image/jpeg",
                new List<byte[]>
                {
                    new byte[] { 0xFF, 0xD8, 0xFF, 0xE0 },
                    new byte[] { 0xFF, 0xD8, 0xFF, 0xE2 },
                    new byte[] { 0xFF, 0xD8, 0xFF, 0xE3 }
                }),
            new FileExtension("jpg","image/jpeg",
                new List<byte[]>
                {
                    new byte[] { 0xFF, 0xD8, 0xFF, 0xE0 },
                    new byte[] { 0xFF, 0xD8, 0xFF, 0xE1 },
                    new byte[] { 0xFF, 0xD8, 0xFF, 0xE8 }
                }),
            new FileExtension("jpgv","video/jpeg"),
            new FileExtension("jpm","video/jpm"),
            new FileExtension("js","text/javascript"),
            new FileExtension("json","application/json"),
            new FileExtension("jsonld","application/ld+json"),
            new FileExtension("kar","audio/midi"),
            new FileExtension("karbon","application/vnd.kde.karbon"),
            new FileExtension("kfo","application/vnd.kde.kformula"),
            new FileExtension("kia","application/vnd.kidspiration"),
            new FileExtension("kml","application/vnd.google-earth.kml+xml"),
            new FileExtension("kmz","application/vnd.google-earth.kmz"),
            new FileExtension("kne","application/vnd.kinar"),
            new FileExtension("kon","application/vnd.kde.kontour"),
            new FileExtension("kpr","application/vnd.kde.kpresenter"),
            new FileExtension("ksp","application/vnd.kde.kspread"),
            new FileExtension("ktx","image/ktx"),
            new FileExtension("ktz","application/vnd.kahootz"),
            new FileExtension("kwd","application/vnd.kde.kword"),
            new FileExtension("lasxml","application/vnd.las.las+xml"),
            new FileExtension("latex","application/x-latex"),
            new FileExtension("lbd","application/vnd.llamagraphics.life-balance.desktop"),
            new FileExtension("lbe","application/vnd.llamagraphics.life-balance.exchange+xml"),
            new FileExtension("les","application/vnd.hhe.lesson-player"),
            new FileExtension("lha","application/octet-stream"),
            new FileExtension("link66","application/vnd.route66.link66+xml"),
            new FileExtension("lrm","application/vnd.ms-lrm"),
            new FileExtension("lsf","video/x-la-asf"),
            new FileExtension("lsx","video/x-la-asf"),
            new FileExtension("ltf","application/vnd.frogans.ltf"),
            new FileExtension("lvp","audio/vnd.lucent.voice"),
            new FileExtension("lwp","application/vnd.lotus-wordpro"),
            new FileExtension("lzh","application/octet-stream"),
            new FileExtension("m13","application/x-msmediaview"),
            new FileExtension("m14","application/x-msmediaview"),
            new FileExtension("m21","application/mp21"),
            new FileExtension("m3u","audio/x-mpegurl"),
            new FileExtension("m3u8","application/vnd.apple.mpegurl"),
            new FileExtension("m4a","audio/mp4a-latm",
                new List<byte[]> { new byte[] { 0x00, 0x00, 0x00, 0x20, 0x66, 0x74, 0x79, 0x70, 0x4D, 0x34, 0x41 } }),
            new FileExtension("m4b","audio/mp4a-latm"),
            new FileExtension("m4p","audio/mp4a-latm"),
            new FileExtension("m4u","video/vnd.mpegurl"),
            new FileExtension("m4v","video/x-m4v"),
            new FileExtension("ma","application/mathematica"),
            new FileExtension("mac","image/x-macpaint"),
            new FileExtension("mads","application/mads+xml"),
            new FileExtension("mag","application/vnd.ecowin.chart"),
            new FileExtension("man","application/x-troff-man"),
            new FileExtension("mathml","application/mathml+xml"),
            new FileExtension("mbk","application/vnd.mobius.mbk"),
            new FileExtension("mbox","application/mbox"),
            new FileExtension("mc1","application/vnd.medcalcdata"),
            new FileExtension("mcd","application/vnd.mcd"),
            new FileExtension("mcurl","text/vnd.curl.mcurl"),
            new FileExtension("mdb","application/x-msaccess"),
            new FileExtension("mdi","image/vnd.ms-modi"),
            new FileExtension("me","application/x-troff-me"),
            new FileExtension("mesh","model/mesh"),
            new FileExtension("meta4","application/metalink4+xml"),
            new FileExtension("mets","application/mets+xml"),
            new FileExtension("mfm","application/vnd.mfmp"),
            new FileExtension("mgp","application/vnd.osgeo.mapguide.package"),
            new FileExtension("mgz","application/vnd.proteus.magazine"),
            new FileExtension("mht","message/rfc822"),
            new FileExtension("mhtml","message/rfc822"),
            new FileExtension("mid","audio/midi",
                new List<byte[]> { new byte[] { 0x4D, 0x54, 0x68, 0x64 } }),
            new FileExtension("midi","audio/midi",
                new List<byte[]> { new byte[] { 0x4D, 0x54, 0x68, 0x64 } }),
            new FileExtension("mif","application/vnd.mif"),
            new FileExtension("mj2","video/mj2"),
            new FileExtension("mjs","text/javascript"),
            new FileExtension("mlp","application/vnd.dolby.mlp"),
            new FileExtension("mmd","application/vnd.chipnuts.karaoke-mmd"),
            new FileExtension("mmf","application/vnd.smaf"),
            new FileExtension("mmr","image/vnd.fujixerox.edmics-mmr"),
            new FileExtension("mny","application/x-msmoney"),
            new FileExtension("mods","application/mods+xml"),
            new FileExtension("mov","video/quicktime",
                new List<byte[]>
                {
                    new byte[] { 0x6D, 0x6F, 0x6F, 0x76 },
                    new byte[] { 0x66, 0x72, 0x65, 0x65 },
                    new byte[] { 0x6D, 0x64, 0x61, 0x74 },
                    new byte[] { 0x77, 0x69, 0x64, 0x65 },
                    new byte[] { 0x70, 0x6E, 0x6F, 0x74 },
                    new byte[] { 0x73, 0x6B, 0x69, 0x70 }
                }),
            new FileExtension("movie","video/x-sgi-movie"),
            new FileExtension("mp2","audio/mpeg"),
            new FileExtension("mp3","audio/mpeg",
                new List<byte[]> { new byte[] { 0x49, 0x44, 0x33 } }),
            new FileExtension("mp4","video/mp4"),
            new FileExtension("mp4a","audio/mp4"),
            new FileExtension("mpa","video/mpeg"),
            new FileExtension("mpc","application/vnd.mophun.certificate"),
            new FileExtension("mpe","video/mpeg"),
            new FileExtension("mpeg","video/mpeg"),
            new FileExtension("mpg","video/mpeg"),
            new FileExtension("mpga","audio/mpeg"),
            new FileExtension("mpkg","application/vnd.apple.installer+xml"),
            new FileExtension("mpm","application/vnd.blueice.multipass"),
            new FileExtension("mpn","application/vnd.mophun.application"),
            new FileExtension("mpp","application/vnd.ms-project"),
            new FileExtension("mpv2","video/mpeg"),
            new FileExtension("mpy","application/vnd.ibm.minipay"),
            new FileExtension("mqy","application/vnd.mobius.mqy"),
            new FileExtension("mrc","application/marc"),
            new FileExtension("mrcx","application/marcxml+xml"),
            new FileExtension("ms","application/x-troff-ms"),
            new FileExtension("mscml","application/mediaservercontrol+xml"),
            new FileExtension("mseq","application/vnd.mseq"),
            new FileExtension("msf","application/vnd.epson.msf"),
            new FileExtension("msg","application/vnd.ms-outlook"),
            new FileExtension("msh","model/mesh"),
            new FileExtension("msl","application/vnd.mobius.msl"),
            new FileExtension("msty","application/vnd.muvee.style"),
            new FileExtension("mts","model/vnd.mts"),
            new FileExtension("mus","application/vnd.musician"),
            new FileExtension("musicxml","application/vnd.recordare.musicxml+xml"),
            new FileExtension("mvb","application/x-msmediaview"),
            new FileExtension("mwf","application/vnd.mfer"),
            new FileExtension("mxf","application/mxf"),
            new FileExtension("mxl","application/vnd.recordare.musicxml"),
            new FileExtension("mxml","application/xv+xml"),
            new FileExtension("mxs","application/vnd.triscape.mxs"),
            new FileExtension("mxu","video/vnd.mpegurl"),
            new FileExtension("n3","text/n3"),
            new FileExtension("nbp","application/vnd.wolfram.player"),
            new FileExtension("nc","application/x-netcdf"),
            new FileExtension("ncx","application/x-dtbncx+xml"),
            new FileExtension("n-gage","application/vnd.nokia.n-gage.symbian.install"),
            new FileExtension("ngdat","application/vnd.nokia.n-gage.data"),
            new FileExtension("nlu","application/vnd.neurolanguage.nlu"),
            new FileExtension("nml","application/vnd.enliven"),
            new FileExtension("nnd","application/vnd.noblenet-directory"),
            new FileExtension("nns","application/vnd.noblenet-sealer"),
            new FileExtension("nnw","application/vnd.noblenet-web"),
            new FileExtension("npx","image/vnd.net-fpx"),
            new FileExtension("nsf","application/vnd.lotus-notes"),
            new FileExtension("nws","message/rfc822"),
            new FileExtension("oa2","application/vnd.fujitsu.oasys2"),
            new FileExtension("oa3","application/vnd.fujitsu.oasys3"),
            new FileExtension("oas","application/vnd.fujitsu.oasys"),
            new FileExtension("obd","application/x-msbinder"),
            new FileExtension("oda","application/oda"),
            new FileExtension("odb","application/vnd.oasis.opendocument.database"),
            new FileExtension("odc","application/vnd.oasis.opendocument.chart"),
            new FileExtension("odf","application/vnd.oasis.opendocument.formula"),
            new FileExtension("odft","application/vnd.oasis.opendocument.formula-template"),
            new FileExtension("odg","application/vnd.oasis.opendocument.graphics"),
            new FileExtension("odi","application/vnd.oasis.opendocument.image"),
            new FileExtension("odm","application/vnd.oasis.opendocument.text-master"),
            new FileExtension("odp","application/vnd.oasis.opendocument.presentation"),
            new FileExtension("ods","application/vnd.oasis.opendocument.spreadsheet"),
            new FileExtension("odt","application/vnd.oasis.opendocument.text"),
            new FileExtension("oga","audio/ogg"),
            new FileExtension("ogg","application/ogg"),
            new FileExtension("ogv","video/ogg"),
            new FileExtension("ogx","application/ogg"),
            new FileExtension("onetoc","application/onenote"),
            new FileExtension("opf","application/oebps-package+xml"),
            new FileExtension("opus","audio/opus"),
            new FileExtension("org","application/vnd.lotus-organizer"),
            new FileExtension("osf","application/vnd.yamaha.openscoreformat"),
            new FileExtension("osfpvg","application/vnd.yamaha.openscoreformat.osfpvg+xml"),
            new FileExtension("otc","application/vnd.oasis.opendocument.chart-template"),
            new FileExtension("otf","font/otf"),
            new FileExtension("otg","application/vnd.oasis.opendocument.graphics-template"),
            new FileExtension("oth","application/vnd.oasis.opendocument.text-web"),
            new FileExtension("oti","application/vnd.oasis.opendocument.image-template"),
            new FileExtension("otp","application/vnd.oasis.opendocument.presentation-template"),
            new FileExtension("ots","application/vnd.oasis.opendocument.spreadsheet-template"),
            new FileExtension("ott","application/vnd.oasis.opendocument.text-template"),
            new FileExtension("oxt","application/vnd.openofficeorg.extension"),
            new FileExtension("p","text/x-pascal"),
            new FileExtension("p10","application/pkcs10"),
            new FileExtension("p12","application/x-pkcs12"),
            new FileExtension("p7b","application/x-pkcs7-certificates"),
            new FileExtension("p7c","application/x-pkcs7-mime"),
            new FileExtension("p7m","application/pkcs7-mime"),
            new FileExtension("p7r","application/x-pkcs7-certreqresp"),
            new FileExtension("p7s","application/pkcs7-signature"),
            new FileExtension("p8","application/pkcs8"),
            new FileExtension("par","text/plain-bas"),
            new FileExtension("paw","application/vnd.pawaafile"),
            new FileExtension("pbd","application/vnd.powerbuilder6"),
            new FileExtension("pbm","image/x-portable-bitmap"),
            new FileExtension("pcf","application/x-font-pcf"),
            new FileExtension("pcl","application/vnd.hp-pcl"),
            new FileExtension("pclxl","application/vnd.hp-pclxl"),
            new FileExtension("pct","image/pict"),
            new FileExtension("pcurl","application/vnd.curl.pcurl"),
            new FileExtension("pcx","image/x-pcx"),
            new FileExtension("pdb","application/octet-stream"),
            new FileExtension("pdf","application/pdf",
                new List<byte[]> { new byte[] { 0x25, 0x50, 0x44, 0x46 } }),
            new FileExtension("pfa","application/x-font-type1"),
            new FileExtension("pfr","application/font-tdpfr"),
            new FileExtension("pfx","application/x-pkcs12"),
            new FileExtension("pgm","image/x-portable-graymap"),
            new FileExtension("pgn","application/x-chess-pgn"),
            new FileExtension("pgp","application/pgp-signature"),
            new FileExtension("php","application/php"),
            new FileExtension("pic","image/x-pict"),
            new FileExtension("pict","image/pict"),
            new FileExtension("pjpeg","image/pjpeg"),
            new FileExtension("pki","application/pkixcmp"),
            new FileExtension("pkipath","application/pkix-pkipath"),
            new FileExtension("pko","application/ynd.ms-pkipko"),
            new FileExtension("plb","application/vnd.3gpp.pic-bw-large"),
            new FileExtension("plc","application/vnd.mobius.plc"),
            new FileExtension("plf","application/vnd.pocketlearn"),
            new FileExtension("pls","application/pls+xml"),
            new FileExtension("pma","application/x-perfmon"),
            new FileExtension("pmc","application/x-perfmon"),
            new FileExtension("pml","application/vnd.ctc-posml"),
            new FileExtension("pmr","application/x-perfmon"),
            new FileExtension("pmw","application/x-perfmon"),
            new FileExtension("png","image/png",
                new List<byte[]> { new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A } }),
            new FileExtension("pnm","image/x-portable-anymap"),
            new FileExtension("pnt","image/x-macpaint"),
            new FileExtension("pntg","image/x-macpaint"),
            new FileExtension("portpkg","application/vnd.macports.portpkg"),
            new FileExtension("pot","application/vnd.ms-powerpoint"),
            new FileExtension("potm","application/vnd.ms-powerpoint.template.macroEnabled.12"),
            new FileExtension("potx","application/vnd.openxmlformats-officedocument.presentationml.template"),
            new FileExtension("ppam","application/vnd.ms-powerpoint.addin.macroEnabled.12"),
            new FileExtension("ppd","application/vnd.cups-ppd"),
            new FileExtension("ppm","image/x-portable-pixmap"),
            new FileExtension("pps","application/vnd.ms-powerpoint"),
            new FileExtension("ppsm","application/vnd.ms-powerpoint.slideshow.macroEnabled.12"),
            new FileExtension("ppsx","application/vnd.openxmlformats-officedocument.presentationml.slideshow"),
            new FileExtension("ppt","application/vnd.ms-powerpoint",
                new List<byte[]>
                {
                    new byte[] { 0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1 },
                    new byte[] { 0x00, 0x6E, 0x1E, 0xF0 },
                    new byte[] { 0x0F, 0x00, 0xE8, 0x03 },
                    new byte[] { 0xA0, 0x46, 0x1D, 0xF0 },
                    new byte[] { 0xFD, 0xFF, 0xFF, 0xFF, 0x43, 0x00, 0x00, 0x00 },
                }),
            new FileExtension("pptm","application/vnd.ms-powerpoint.presentation.macroEnabled.12"),
            new FileExtension("pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation",
                new List<byte[]>
                {
                    new byte[] { 0x50, 0x4B, 0x03, 0x04 },
                    new byte[] { 0x50, 0x4B, 0x03, 0x04, 0x14, 0x00, 0x06, 0x00 }
                }),
            new FileExtension("prc","application/x-mobipocket-ebook"),
            new FileExtension("pre","application/vnd.lotus-freelance"),
            new FileExtension("prf","application/pics-rules"),
            new FileExtension("ps","application/postscript"),
            new FileExtension("psb","application/vnd.3gpp.pic-bw-small"),
            new FileExtension("psd","image/vnd.adobe.photoshop"),
            new FileExtension("psf","application/x-font-linux-psf"),
            new FileExtension("pskcxml","application/pskc+xml"),
            new FileExtension("ptid","application/vnd.pvi.ptid1"),
            new FileExtension("pub","application/x-mspublisher"),
            new FileExtension("pvb","application/vnd.3gpp.pic-bw-var"),
            new FileExtension("pwn","application/vnd.3m.post-it-notes"),
            new FileExtension("pya","audio/vnd.ms-playready.media.pya"),
            new FileExtension("pyv","video/vnd.ms-playready.media.pyv"),
            new FileExtension("qam","application/vnd.epson.quickanime"),
            new FileExtension("qbo","application/vnd.intu.qbo"),
            new FileExtension("qfx","application/vnd.intu.qfx"),
            new FileExtension("qps","application/vnd.publishare-delta-tree"),
            new FileExtension("qt","video/quicktime"),
            new FileExtension("qti","image/x-quicktime"),
            new FileExtension("qtif","image/x-quicktime"),
            new FileExtension("qxd","application/vnd.quark.quarkxpress"),
            new FileExtension("ra","audio/x-pn-realaudio"),
            new FileExtension("ram","audio/x-pn-realaudio"),
            new FileExtension("rar","application/x-rar-compressed"),
            new FileExtension("ras","image/x-cmu-raster"),
            new FileExtension("rcprofile","application/vnd.ipunplugged.rcprofile"),
            new FileExtension("rdf","application/rdf+xml"),
            new FileExtension("rdz","application/vnd.data-vision.rdz"),
            new FileExtension("rep","application/vnd.businessobjects"),
            new FileExtension("res","application/x-dtbresource+xml"),
            new FileExtension("rgb","image/x-rgb"),
            new FileExtension("rif","application/reginfo+xml"),
            new FileExtension("rip","audio/vnd.rip"),
            new FileExtension("rl","application/resource-lists+xml"),
            new FileExtension("rlc","image/vnd.fujixerox.edmics-rlc"),
            new FileExtension("rld","application/resource-lists-diff+xml"),
            new FileExtension("rm","application/vnd.rn-realmedia"),
            new FileExtension("rmi","audio/mid"),
            new FileExtension("rmp","audio/x-pn-realaudio-plugin"),
            new FileExtension("rms","application/vnd.jcp.javame.midlet-rms"),
            new FileExtension("rnc","application/relax-ng-compact-syntax"),
            new FileExtension("roff","application/x-troff"),
            new FileExtension("rp9","application/vnd.cloanto.rp9"),
            new FileExtension("rpss","application/vnd.nokia.radio-presets"),
            new FileExtension("rpst","application/vnd.nokia.radio-preset"),
            new FileExtension("rq","application/sparql-query"),
            new FileExtension("rs","application/rls-services+xml"),
            new FileExtension("rsd","application/rsd+xml"),
            new FileExtension("rss, xml","application/rss+xml"),
            new FileExtension("rtf","application/rtf"),
            new FileExtension("rtx","text/richtext"),
            new FileExtension("s","text/x-asm"),
            new FileExtension("saf","application/vnd.yamaha.smaf-audio"),
            new FileExtension("sbml","application/sbml+xml"),
            new FileExtension("sc","application/vnd.ibm.secure-container"),
            new FileExtension("scd","application/x-msschedule"),
            new FileExtension("scm","application/vnd.lotus-screencam"),
            new FileExtension("scq","application/scvp-cv-request"),
            new FileExtension("scs","application/scvp-cv-response"),
            new FileExtension("sct","text/scriptlet"),
            new FileExtension("scurl","text/vnd.curl.scurl"),
            new FileExtension("sda","application/vnd.stardivision.draw"),
            new FileExtension("sdc","application/vnd.stardivision.calc"),
            new FileExtension("sdd","application/vnd.stardivision.impress"),
            new FileExtension("sdkm","application/vnd.solent.sdkm+xml"),
            new FileExtension("sdp","application/sdp"),
            new FileExtension("sdw","application/vnd.stardivision.writer"),
            new FileExtension("see","application/vnd.seemail"),
            new FileExtension("seed","application/vnd.fdsn.seed"),
            new FileExtension("sema","application/vnd.sema"),
            new FileExtension("semd","application/vnd.semd"),
            new FileExtension("semf","application/vnd.semf"),
            new FileExtension("ser","application/java-serialized-object"),
            new FileExtension("setpay","application/set-payment-initiation"),
            new FileExtension("setreg","application/set-registration-initiation"),
            new FileExtension("sfd-hdstx","application/vnd.hydrostatix.sof-data"),
            new FileExtension("sfs","application/vnd.spotfire.sfs"),
            new FileExtension("sgl","application/vnd.stardivision.writer-global"),
            new FileExtension("sgm","text/sgml"),
            new FileExtension("sgml","text/sgml"),
            new FileExtension("sh","application/x-sh"),
            new FileExtension("shar","application/x-shar"),
            new FileExtension("shf","application/shf+xml"),
            new FileExtension("silo","model/mesh"),
            new FileExtension("sis","application/vnd.symbian.install"),
            new FileExtension("sit","application/x-stuffit"),
            new FileExtension("sitx","application/x-stuffitx"),
            new FileExtension("skd","application/x-koan"),
            new FileExtension("skm","application/x-koan"),
            new FileExtension("skp","application/vnd.koan"),
            new FileExtension("skt","application/x-koan"),
            new FileExtension("sldm","application/vnd.ms-powerpoint.slide.macroenabled.12"),
            new FileExtension("sldx","application/vnd.openxmlformats-officedocument.presentationml.slide"),
            new FileExtension("slt","application/vnd.epson.salt"),
            new FileExtension("sm","application/vnd.stepmania.stepchart"),
            new FileExtension("smf","application/vnd.stardivision.math"),
            new FileExtension("smi","application/smil+xml"),
            new FileExtension("smil","application/smil"),
            new FileExtension("snd","audio/basic"),
            new FileExtension("snf","application/x-font-snf"),
            new FileExtension("so","application/octet-stream"),
            new FileExtension("spc","application/x-pkcs7-certificates"),
            new FileExtension("spf","application/vnd.yamaha.smaf-phrase"),
            new FileExtension("spl","application/x-futuresplash"),
            new FileExtension("spot","text/vnd.in3d.spot"),
            new FileExtension("spp","application/scvp-vp-response"),
            new FileExtension("spq","application/scvp-vp-request"),
            new FileExtension("src","application/x-wais-source"),
            new FileExtension("sru","application/sru+xml"),
            new FileExtension("srx","application/sparql-results+xml"),
            new FileExtension("sse","application/vnd.kodak-descriptor"),
            new FileExtension("ssf","application/vnd.epson.ssf"),
            new FileExtension("ssml","application/ssml+xml"),
            new FileExtension("sst","application/vnd.ms-pkicertstore"),
            new FileExtension("st","application/vnd.sailingtracker.track"),
            new FileExtension("stc","application/vnd.sun.xml.calc.template"),
            new FileExtension("std","application/vnd.sun.xml.draw.template"),
            new FileExtension("stf","application/vnd.wt.stf"),
            new FileExtension("sti","application/vnd.sun.xml.impress.template"),
            new FileExtension("stk","application/hyperstudio"),
            new FileExtension("stl","application/vnd.ms-pki.stl"),
            new FileExtension("stm","text/html"),
            new FileExtension("str","application/vnd.pg.format"),
            new FileExtension("stw","application/vnd.sun.xml.writer.template"),
            new FileExtension("sub","image/vnd.dvb.subtitle"),
            new FileExtension("sus","application/vnd.sus-calendar"),
            new FileExtension("sv4cpio","application/x-sv4cpio"),
            new FileExtension("sv4crc","application/x-sv4crc"),
            new FileExtension("svc","application/vnd.dvb.service"),
            new FileExtension("svd","application/vnd.svd"),
            new FileExtension("svg","image/svg+xml"),
            new FileExtension("swf","application/x-shockwave-flash"),
            new FileExtension("swi","application/vnd.aristanetworks.swi"),
            new FileExtension("sxc","application/vnd.sun.xml.calc"),
            new FileExtension("sxd","application/vnd.sun.xml.draw"),
            new FileExtension("sxg","application/vnd.sun.xml.writer.global"),
            new FileExtension("sxi","application/vnd.sun.xml.impress"),
            new FileExtension("sxm","application/vnd.sun.xml.math"),
            new FileExtension("sxw","application/vnd.sun.xml.writer"),
            new FileExtension("t","text/troff"),
            new FileExtension("tao","application/vnd.tao.intent-module-archive"),
            new FileExtension("tar","application/x-tar"),
            new FileExtension("tcap","application/vnd.3gpp2.tcap"),
            new FileExtension("tcl","application/x-tcl"),
            new FileExtension("teacher","application/vnd.smart.teacher"),
            new FileExtension("tei","application/tei+xml"),
            new FileExtension("tex","application/x-tex"),
            new FileExtension("texi","application/x-texinfo"),
            new FileExtension("texinfo","application/x-texinfo"),
            new FileExtension("tfi","application/thraud+xml"),
            new FileExtension("tfm","application/x-tex-tfm"),
            new FileExtension("tgz","application/x-compressed"),
            new FileExtension("thmx","application/vnd.ms-officetheme"),
            new FileExtension("tif","image/tiff"),
            new FileExtension("tiff","image/tiff"),
            new FileExtension("tmo","application/vnd.tmobile-livetv"),
            new FileExtension("torrent","application/x-bittorrent"),
            new FileExtension("tpl","application/vnd.groove-tool-template"),
            new FileExtension("tpt","application/vnd.trid.tpt"),
            new FileExtension("tr","application/x-troff"),
            new FileExtension("tra","application/vnd.trueapp"),
            new FileExtension("trm","application/x-msterminal"),
            new FileExtension("ts","video/mp2t"),
            new FileExtension("tsd","application/timestamped-data"),
            new FileExtension("tsv","text/tab-separated-values"),
            new FileExtension("ttf","font/ttf"),
            new FileExtension("ttl","text/turtle"),
            new FileExtension("twbx","application/twbx"),
            new FileExtension("twd","application/vnd.simtech-mindmapper"),
            new FileExtension("txd","application/vnd.genomatix.tuxedo"),
            new FileExtension("txf","application/vnd.mobius.txf"),
            new FileExtension("txt","text/plain"),
            new FileExtension("ufd","application/vnd.ufdl"),
            new FileExtension("uls","text/iuls"),
            new FileExtension("umj","application/vnd.umajin"),
            new FileExtension("unityweb","application/vnd.unity"),
            new FileExtension("uoml","application/vnd.uoml+xml"),
            new FileExtension("uri","text/uri-list"),
            new FileExtension("ustar","application/x-ustar"),
            new FileExtension("utz","application/vnd.uiq.theme"),
            new FileExtension("uu","text/x-uuencode"),
            new FileExtension("uva","audio/vnd.dece.audio"),
            new FileExtension("uvh","video/vnd.dece.hd"),
            new FileExtension("uvi","image/vnd.dece.graphic"),
            new FileExtension("uvm","video/vnd.dece.mobile"),
            new FileExtension("uvp","video/vnd.dece.pd"),
            new FileExtension("uvs","video/vnd.dece.sd"),
            new FileExtension("uvu","video/vnd.uvvu.mp4"),
            new FileExtension("uvv","video/vnd.dece.video"),
            new FileExtension("vcd","application/x-cdlink"),
            new FileExtension("vcf","text/x-vcard"),
            new FileExtension("vcg","application/vnd.groove-vcard"),
            new FileExtension("vcs","text/x-vcalendar"),
            new FileExtension("vcx","application/vnd.vcx"),
            new FileExtension("vis","application/vnd.visionary"),
            new FileExtension("viv","video/vnd.vivo"),
            new FileExtension("vrml","model/vrml"),
            new FileExtension("vsd","application/vnd.visio"),
            new FileExtension("vsdx","application/vnd.visio2013"),
            new FileExtension("vsf","application/vnd.vsf"),
            new FileExtension("vtu","model/vnd.vtu"),
            new FileExtension("vxml","application/voicexml+xml"),
            new FileExtension("wad","application/x-doom"),
            new FileExtension("wav","audio/wav",
                new List<byte[]>() { new byte[] { 0x52, 0x49, 0x46, 0x46 } }),
            new FileExtension("wax","audio/x-ms-wax"),
            new FileExtension("wbmp","image/vnd.wap.wbmp"),
            new FileExtension("wbmxl","application/vnd.wap.wbxml"),
            new FileExtension("wbs","application/vnd.criticaltools.wbs+xml"),
            new FileExtension("wbxml","application/vnd.wap.wbxml"),
            new FileExtension("wcm","application/vnd.ms-works"),
            new FileExtension("wdb","application/vnd.ms-works"),
            new FileExtension("weba","audio/webm"),
            new FileExtension("webm","video/webm"),
            new FileExtension("webp","image/webp"),
            new FileExtension("wg","application/vnd.pmi.widget"),
            new FileExtension("wgt","application/widget"),
            new FileExtension("wks","application/vnd.ms-works"),
            new FileExtension("wm","video/x-ms-wm"),
            new FileExtension("wma","audio/x-ms-wma"),
            new FileExtension("wmd","application/x-ms-wmd"),
            new FileExtension("wmf","application/x-msmetafile"),
            new FileExtension("wml","text/vnd.wap.wml"),
            new FileExtension("wmlc","application/vnd.wap.wmlc"),
            new FileExtension("wmls","text/vnd.wap.wmlscript"),
            new FileExtension("wmlsc","application/vnd.wap.wmlscriptc"),
            new FileExtension("wmv","video/x-ms-wmv"),
            new FileExtension("wmx","video/x-ms-wmx"),
            new FileExtension("wmz","application/x-ms-wmz"),
            new FileExtension("woff","font/woff"),
            new FileExtension("woff2","font/woff2"),
            new FileExtension("wpd","application/vnd.wordperfect"),
            new FileExtension("wpl","application/vnd.ms-wpl"),
            new FileExtension("wps","application/vnd.ms-works"),
            new FileExtension("wqd","application/vnd.wqd"),
            new FileExtension("wri","application/x-mswrite"),
            new FileExtension("wrl","model/vrml"),
            new FileExtension("wrz","x-world/x-vrml"),
            new FileExtension("wsdl","application/wsdl+xml"),
            new FileExtension("wspolicy","application/wspolicy+xml"),
            new FileExtension("wtb","application/vnd.webturbo"),
            new FileExtension("wvx","video/x-ms-wvx"),
            new FileExtension("x3d","application/vnd.hzn-3d-crossword"),
            new FileExtension("xaf","x-world/x-vrml"),
            new FileExtension("xap","application/x-silverlight-app"),
            new FileExtension("xar","application/vnd.xara"),
            new FileExtension("xbap","application/x-ms-xbap"),
            new FileExtension("xbd","application/vnd.fujixerox.docuworks.binder"),
            new FileExtension("xbm","image/x-xbitmap"),
            new FileExtension("xdf","application/xcap-diff+xml"),
            new FileExtension("xdm","application/vnd.syncml.dm+xml"),
            new FileExtension("xdp","application/vnd.adobe.xdp+xml"),
            new FileExtension("xdssc","application/dssc+xml"),
            new FileExtension("xdw","application/vnd.fujixerox.docuworks"),
            new FileExtension("xenc","application/xenc+xml"),
            new FileExtension("xer","application/patch-ops-error+xml"),
            new FileExtension("xfdf","application/vnd.adobe.xfdf"),
            new FileExtension("xfdl","application/vnd.xfdl"),
            new FileExtension("xht","application/xhtml+xml"),
            new FileExtension("xhtml","application/xhtml+xml"),
            new FileExtension("xif","image/vnd.xiff"),
            new FileExtension("xla","application/vnd.ms-excel"),
            new FileExtension("xlam","application/vnd.ms-excel.addin.macroEnabled.12"),
            new FileExtension("xlc","application/vnd.ms-excel"),
            new FileExtension("xlm","application/vnd.ms-excel"),
            new FileExtension("xls","application/vnd.ms-excel",
                new List<byte[]>
                {
                    new byte[] { 0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1 },
                    new byte[] { 0x09, 0x08, 0x10, 0x00, 0x00, 0x06, 0x05, 0x00 },
                    new byte[] { 0xFD, 0xFF, 0xFF, 0xFF }
                }),
            new FileExtension("xlsb","application/vnd.ms-excel.sheet.binary.macroEnabled.12"),
            new FileExtension("xlsm","application/vnd.ms-excel.sheet.macroEnabled.12"),
            new FileExtension("xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                new List<byte[]> { new byte[] { 0x50, 0x4B, 0x03, 0x04 } }),
            new FileExtension("xlt","application/vnd.ms-excel"),
            new FileExtension("xltm","application/vnd.ms-excel.template.macroEnabled.12"),
            new FileExtension("xltx","application/vnd.openxmlformats-officedocument.spreadsheetml.template"),
            new FileExtension("xlw","application/vnd.ms-excel"),
            new FileExtension("xml","application/xml"),
            new FileExtension("xo","application/vnd.olpc-sugar"),
            new FileExtension("xof","x-world/x-vrml"),
            new FileExtension("xop","application/xop+xml"),
            new FileExtension("xpi","application/x-xpinstall"),
            new FileExtension("xpm","image/x-xpixmap"),
            new FileExtension("xpr","application/vnd.is-xpr"),
            new FileExtension("xps","application/vnd.ms-xpsdocument"),
            new FileExtension("xpw","application/vnd.intercon.formnet"),
            new FileExtension("xsl","application/xml"),
            new FileExtension("xslt","application/xslt+xml"),
            new FileExtension("xsm","application/vnd.syncml+xml"),
            new FileExtension("xspf","application/xspf+xml"),
            new FileExtension("xul","application/vnd.mozilla.xul+xml"),
            new FileExtension("xwd","image/x-xwindowdump"),
            new FileExtension("xyz","chemical/x-xyz"),
            new FileExtension("yaml","text/yaml"),
            new FileExtension("yang","application/yang"),
            new FileExtension("yin","application/yin+xml"),
            new FileExtension("z","application/x-compress"),
            new FileExtension("zaz","application/vnd.zzazz.deck+xml"),
            new FileExtension("zip","application/zip",
                new List<byte[]>
                {
                    new byte[] { 0x50, 0x4B, 0x03, 0x04 },
                    new byte[] { 0x50, 0x4B, 0x4C, 0x49, 0x54, 0x55 },
                    new byte[] { 0x50, 0x4B, 0x53, 0x70, 0x58 },
                    new byte[] { 0x50, 0x4B, 0x05, 0x06 },
                    new byte[] { 0x50, 0x4B, 0x07, 0x08 },
                    new byte[] { 0x57, 0x69, 0x6E, 0x5A, 0x69, 0x70 }
                }),
            new FileExtension("zir","application/vnd.zul"),
            new FileExtension("zmm","application/vnd.handheld-entertainment+xml")
        }.ToDictionary(fe => fe.Extension);

        /// <summary>
        /// Returns set of standard document extensions (docx, txt, xls, etc.).
        /// </summary>
        public static readonly IEnumerable<string> CommonDocumentExtensions = new HashSet<string>()
        {
            "doc", "docx", "pdf", "txt", "xls", "xlsx", "pptx", "ppt", "csv"
        };

        /// <summary>
        /// Returns set of standard image extensions (jpg, png, etc.).
        /// </summary>
        public static readonly IEnumerable<string> CommonImageExtensions = new HashSet<string>()
        {
            "jpg", "jpeg", "png", "gif", "svg", "bmp"
        };

        /// <summary>
        /// Returns set of standard document and image file extensions.
        /// </summary>
        public static readonly IEnumerable<string> CommonFileExtensions
            = new HashSet<string>(CommonDocumentExtensions.Union(CommonImageExtensions));

        /// <summary>
        /// Returns set of standard audio file extensions.
        /// </summary>
        public static readonly IEnumerable<string> CommonAudioExtensions = new HashSet<string>()
        {
            "mp3", "wav", "m4a", "au", "mid", "midi"
        };

        /// <summary>
        /// Returns set of standard video extensions.
        /// </summary>
        public static readonly IEnumerable<string> CommonVideoExtensions = new HashSet<string>()
        {
            "mp4", "mov", "movie", "mpeg", "mp2", "mpa"
        };

        /// <summary>
        /// Returns set of image, audio, and video file extensions
        /// </summary>
        public static readonly IEnumerable<string> CommonMediaExtensions
            = new HashSet<string>(CommonImageExtensions.Union(CommonAudioExtensions).Union(CommonVideoExtensions));

        /// <summary>
        /// Singleton instance.
        /// </summary>
        public static FileExtensions Instance = new FileExtensions(); // NOTE: this must be at the bottom of the class
    }
}
