using Common.Core.Domain;
using Common.Core.Validation;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Common.EntityFrameworkCore
{
    public static class LookupEntityBuilderExtensions
    {
        //
        // Summary:
        //     Configure standard LookupEntity properties. Id assumed as Key and Name required
        //     with length of 200.
        //
        // Parameters:
        //   builder:
        //
        //   generateIdOnDatabase:
        //     Option to have Id generated by database (identity specification). Defaults to
        //     false with intent to be used with enum type.
        //
        // Type parameters:
        //   T:
        //     Lookup entity type.
        public static EntityTypeBuilder<T> ConfigureLookupEntityProperties<T>(this EntityTypeBuilder<T> builder, bool generateIdOnDatabase = false) where T : class, ILookupEntity
        {
            if (!generateIdOnDatabase)
            {
                builder.Property((T x) => x.Id).ValueGeneratedNever();
            }

            builder.Property((T x) => x.Name).HasMaxLength(200).IsRequired();
            return builder;
        }

        //
        // Summary:
        //     Configure standard LookupEntity properties. Id assumed as Key, not generated
        //     by database, and Name required with length of 200. Includes callback for seeding
        //     based on a provided enum type of TEnum. Callback function is called per enum
        //     type to build the lookup entity type for automatic seeding.
        //
        // Parameters:
        //   builder:
        //
        //   entityObjectBuilder:
        //     Callback function to create lookup object based on the provided enum.
        //
        // Type parameters:
        //   TEntity:
        //     Lookup entity type.
        //
        //   TEnum:
        //     Enum type representing the lookup entity type.
        public static EntityTypeBuilder<TEntity> ConfigureLookupEntityProperties<TEntity, TEnum>(this EntityTypeBuilder<TEntity> builder, Func<TEnum, TEntity> entityObjectBuilder) where TEntity : class, ILookupEntity where TEnum : Enum
        {
            return builder.ConfigureLookupEntityProperties().SeedLookups(entityObjectBuilder);
        }

        //
        // Summary:
        //     Seed lookup values based on provided enum type TEnum. Callback function is called
        //     per enum type to build the lookup entity type for automatic seeding.
        //
        // Parameters:
        //   builder:
        //
        //   entityObjectBuilder:
        //     Callback function to create lookup object based on the provided enum.
        //
        // Type parameters:
        //   TEntity:
        //     Lookup entity type.
        //
        //   TEnum:
        //     Enum type representing the lookup entity type.
        public static EntityTypeBuilder<TEntity> SeedLookups<TEntity, TEnum>(this EntityTypeBuilder<TEntity> builder, Func<TEnum, TEntity> entityObjectBuilder) where TEntity : class, ILookupEntity where TEnum : Enum
        {
            Guard.IsNotNull(entityObjectBuilder, "entityObjectBuilder");
            TEnum[] array = (TEnum[])Enum.GetValues(typeof(TEnum));
            if (array != null && array.Length != 0)
            {
                TEnum[] array2 = array;
                foreach (TEnum arg in array2)
                {
                    builder.HasData(entityObjectBuilder(arg));
                }
            }

            return builder;
        }
    }
}
