using Common.Core.Domain;
using Common.Core.Validation;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Common.EntityFrameworkCore
{
    public static class LookupEntityBuilderExtensions
    {
        /// <summary>
        /// Configure standard LookupEntity properties. 
        /// Id assumed as Key and Name required with length of 200.
        /// </summary>
        /// <typeparam name="T">Lookup entity type.</typeparam>
        /// <param name="builder"></param>
        /// <param name="generateIdOnDatabase">
        /// Option to have Id generated by database (identity specification). 
        /// Defaults to false with intent to be used with enum type.
        /// </param>
        /// <returns></returns>
        public static EntityTypeBuilder<T> ConfigureLookupEntityProperties<T>(
           this EntityTypeBuilder<T> builder,
           bool generateIdOnDatabase = false)
           where T : class, ILookupEntity
        {
            if (!generateIdOnDatabase)
                builder.Property(x => x.Id).ValueGeneratedNever();

            builder.Property(x => x.Name).HasMaxLength(200).IsRequired();

            return builder;
        }

        /// <summary>
        /// Configure standard LookupEntity properties. 
        /// Id assumed as Key, not generated by database, and Name required with length of 200.
        /// Includes callback for seeding based on a provided enum type of <typeparamref name="TEnum"/>.
        /// Callback function is called per enum type to build the lookup entity type for automatic seeding.
        /// </summary>
        /// <typeparam name="TEntity">Lookup entity type.</typeparam>
        /// <typeparam name="TEnum">Enum type representing the lookup entity type.</typeparam>
        /// <param name="builder"></param>
        /// <param name="entityObjectBuilder">Callback function to create lookup object based on the provided enum.</param>
        /// <returns></returns>
        public static EntityTypeBuilder<TEntity> ConfigureLookupEntityProperties<TEntity, TEnum>(
           this EntityTypeBuilder<TEntity> builder,
           Func<TEnum, TEntity> entityObjectBuilder)
            where TEntity : class, ILookupEntity
            where TEnum : Enum
        {
            return builder.ConfigureLookupEntityProperties()
                          .SeedLookups(entityObjectBuilder);
        }

        /// <summary>
        /// Seed lookup values based on provided enum type <typeparamref name="TEnum"/>.
        /// Callback function is called per enum type to build the lookup entity type for automatic seeding.
        /// </summary>
        /// <typeparam name="TEntity">Lookup entity type.</typeparam>
        /// <typeparam name="TEnum">Enum type representing the lookup entity type.</typeparam>
        /// <param name="builder"></param>
        /// <param name="entityObjectBuilder">Callback function to create lookup object based on the provided enum.</param>
        /// <returns></returns>
        public static EntityTypeBuilder<TEntity> SeedLookups<TEntity, TEnum>(
           this EntityTypeBuilder<TEntity> builder,
           Func<TEnum, TEntity> entityObjectBuilder)
            where TEntity : class, ILookupEntity
            where TEnum : Enum
        {
            Guard.IsNotNull(entityObjectBuilder, nameof(entityObjectBuilder));

            var enumValues = (TEnum[])Enum.GetValues(typeof(TEnum));
            if (enumValues != null && enumValues.Length > 0)
            {
                foreach (var enumValue in enumValues)
                {
                    builder.HasData(entityObjectBuilder.Invoke(enumValue));
                }
            }

            return builder;
        }
    }
}